cipherText = "raffbzckdlbadcajzmrarzbfrhrbznbrwfblbasmcbpdcajzkmpwpeebdcajzkmpmswfbrrwubznmhunwfbrrwubmcucmhjmsfbrrwubrfwanwxbwekssbcbpzlbaznwpmznbcrwrkupkskdwpzekrwexwpzwubmsraffbzckddkjnbcrkrznblbafwpwubfbpzpbdbrrwcazmhrbznbfrbdhcbvabwdnekrzkpdzjwkcmsdmffhpkdwzkpujwczkbrfhrzkebwvvarnwcbwekssbcbpzlbawpejbcnwjrbwdndkjnbczbozbodnwpubewrgbvvznbphftbcmslbarcbihkcbekpdcbwrbrwrznbrihwcbmsznbphftbcmspbzgmclfbftbcrgnkdnxbcaihkdlvacbihkcbrdmfjvbolbafwpwubfbpzrdnbfbrzmlbbjznbfwvvrzcwkunzwperbdcbzznbeksskdhvzamsrbdhcbvabrzwtvkrnkpuwrbdcbzlbatbzgbbpzgmdmffhpkdwzkpujwczkbrgnbpwrbdhcbdnwppbvembrpmzwvcbweabokrztbzgbbpznbfwvrmjcbrbpzrwdnkdlbpwpebuujcmtvbfgnkdnkrwdmprkebcwtvbjcwdzkdwvmtrzwdvbsmcdcajzmucwjnahrbcrkpznbcbwvgmcvekpwucmhpetcbwlkpujwjbcgnkzskbveeksskbwpefwczkpnbvvfwpjcmjmrbeznbpmzkmpmsjhtvkdlbawvrmfmcbubpbcwvvadwvvbewraffbzckdlbadcajzmucwjnakpgnkdnzgmekssbcbpzthzfwznbfwzkdwvvacbvwzbelbarwcbhrbewjhtvkdlbawpewjckxwzblbawjhtvkdlbararzbfkrrmdmprzchdzbeznwzdwvdhvwzkmpmsmpblbaznbjckxwzblbakrdmfjhzwzkmpwvvakpsbwrktvbscmfznbmznbcznbjhtvkdlbabxbpznmhunznbawcbpbdbrrwckvacbvwzbekprzbwetmznlbarwcbubpbcwzberbdcbzvawrwpkpzbccbvwzbejwkcznbnkrzmckwpewxkelwnpebrdcktbejhtvkdlbadcajzmucwjnawrznbfmrzcbxmvhzkmpwcapbgdmpdbjzkpznbskbverkpdbjmvawvjnwtbzkdrhtrzkzhzkmpbfbcubekpznbcbpwkrrwpdb"

alphabet = "abcdefghijklmnopqrstuvwxyz"

frequencies = []

for letter in alphabet:
    frequencies.append(cipherText.count(letter) / len(cipherText))

print(frequencies)
